import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import MapExample from '../components/Maps/MapExample';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="w-full h-full">
        <section>
          <h2>Logistics Example</h2>
        </section>
        <section className="w-full h-full px-8 py-4">
          <MapExample/>
        </section>
          
        
      </main>
    </>
  )
}
